name       : libstrophe
version    : 0.12.0
release    : 4
source     :
    - https://github.com/strophe/libstrophe/releases/download/0.12.0/libstrophe-0.12.0.tar.gz : 7f7b7b8bdc268ff1b9eed6a9796777a6f8fac62b40fe316cfe91323696805b64
homepage   : http://strophe.im/libstrophe/
license    :
    - GPL-3.0-only
    - MIT
component  : programming.library
summary    : A simple, lightweight C library for writing XMPP clients
description: |
    libstrophe is a lightweight XMPP client library written in C. It has minimal dependencies and is configurable for various environments.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # build with --disable-static cause issues with the linker
    rm $installdir/%libdir%/*.a
check      : |
    %make check
