name       : libstrophe
version    : 0.9.2
release    : 2
source     :
    - https://github.com/strophe/libstrophe/releases/download/0.9.2/libstrophe-0.9.2.tar.xz : 63625d12f094e198c01edc97460fdba3a9bba9f0ada10f7f8c82dc5c151ff016
license    :
    - GPL-3.0-only
    - MIT
component  : programming.library
summary    : A simple, lightweight C library for writing XMPP clients
description: |
    libstrophe is a lightweight XMPP client library written in C. It has minimal dependencies and is configurable for various environments.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # build with --disable-static cause issues with the linker
    rm $installdir/%libdir%/*.a
check      : |
    %make check
